### ISSUE TITLE
MCR

### ISSUE THREAD

**Issue by tsimants** [animalcharade/synemabot#22]
Everytime Michael updates this, I get one step further away from that sweet sweet black parade

**Comment by animalcharade** [comment]
I will _LOOK_ at this issue soon! [https://www.youtube.com/watch?v=0f03ZKjtuKM](url)

**Comment by tsimants** [comment]
I wanna say this is harassment and tyranny

**Comment by animalcharade** [comment]
The bot has an appropriate amount of MCR as of now.
